export const state = () => ({
  editorConfig: {
    width: "auto",
    plugins: [
      "Bold",
      "Link",
      "List",
      "FontSize",
      "Alignment",
      "AutoImage",
      "Autoformat",
      "BlockQuote",
      "Bold",
      "CloudServices",
      "Code",
      "CodeBlock",
      "Essentials",
      "FontBackgroundColor",
      "FontColor",
      "FontFamily",
      "FontSize",
      "Heading",
      "Highlight",
      "HorizontalLine",
      "Image",
      "ImageCaption",
      "ImageInsert",
      "ImageResize",
      "ImageStyle",
      "ImageToolbar",
      "ImageUpload",
      "Indent",
      "IndentBlock",
      "Italic",
      "Link",
      "List",
      "ListStyle",
      "MathType",
      "MediaEmbed",
      "MediaEmbedToolbar",
      "PageBreak",
      "Paragraph",
      "PasteFromOffice",
      "RemoveFormat",
      "SimpleUploadAdapter",
      "SpecialCharacters",
      "SpecialCharactersArrows",
      "SpecialCharactersCurrency",
      "SpecialCharactersLatin",
      "SpecialCharactersMathematical",
      "SpecialCharactersText",
      //"Strikethrough",
      "Subscript",
      "Superscript",
      "Table",
      "TableCellProperties",
      "TableProperties",
      "TableToolbar",
      "TextTransformation",
      "TodoList",
      "Underline",
      "WordCount",
    ],
    simpleUpload: {
      // The URL that the images are uploaded to.
      uploadUrl: "http://localhost:5000/uploads",
    },
  },
});

export const getters = {};

export const mutations = {};

export const actions = {};
